### ISSUE TITLE
交叉の親が1つだけのことがある

### ISSUE THREAD

**Issue by ty-v1** [kusumotolab/kGenProg#567]
交叉関連のオプションを
* FirstVariantSelection -> RandomVariantSelection
* SecondVariantSelection -> TestSimilaritySelection
に設定した時に，親が1つしかない交叉が行われることがある

KGPのバグか可視化ツールのバグか確認する必要がある．

**Comment by YoshikiHigo** [comment]
これだけだとバグを再現しづらいです．
対象のバグ，設定情報なと，バグの再現に必要な情報をください．

**Comment by ty-v1** [comment]
忘れていました
追記です

* 発生を確認したバグID : Math2
## 再現方法
```bash
# Math2のディレクトリに移動
cd xxxx
# 依存jarダウンロード
# hamcrest.jarが手元にある場合は不要
mvn dependency:copy-dependencies -DoutputDirectory=lib


```

## tomlの形式
```toml
max-generation=400
mutation-generating-count=2
crossover-generating-count=40
headcount=20

src=["./src/main/java"]
test=["./src/test/java"]
# hamcrest.jarへのパス
cp=["<path_to_hamcrest>"]
exec-test=["org.apache.commons.math3.distribution.HypergeometricDistributionTest"]
time-limit=3600
```
